name: 'Use flippy script to package Armvirt as OpenWrt'
author: 'womade'
description: 'Package Armvirt as OpenWrt. Support Amlogic S9xxx STB, vplus, beikeyun and l1pro, etc.'
inputs:
  mode:
    description: 'Choose script.'
    required: false
    default: 'flippy'

runs:
  using: "composite"
  steps: 
    - run: ${GITHUB_ACTION_PATH}/openwrt_${{ inputs.mode }}.sh
      shell: bash
      
branding:
  icon: 'terminal'
  color: 'gray-dark'
